[settings]
experimental = true

[hooks]
enter = "if [ -f lefthook.yml ]; then lefthook install; fi"

[tools]
bun = "1.3.10"

[tasks.check]
env.CLI = "/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli"
run = '"$CLI" ./build/karabiner.json'

[tasks.build]
run = "bun src/build.ts && mise run format"

[tasks."lint"]
run = "bun run biome lint --write src/"

[tasks.format]
run = "bun run biome check --write src/ build/karabiner.json"

[tasks.sync]
env.DOTFILES= "{{ exec(command='ghq root') }}/github.com/y-writings/dotfiles/nix/home/files/karabiner"
run = 'cp -p build/karabiner.json "$DOTFILES"/karabiner.json'
