import { map } from "karabiner.ts"

export const simpleModPrimitiveKeyRule = () => {
  return [
    map("caps_lock").to("left_control"),
    map("delete_or_backspace").toNone(),
    map("escape").toNone(),
    map("hyphen").toNone(),
    map("equal_sign").toNone(),
    map("grave_accent_and_tilde").toNone(),
    map("1").toNone(),
    map("2").toNone(),
    map("3").toNone(),
    map("4").toNone(),
    map("5").toNone(),
    map("6").toNone(),
    map("7").toNone(),
    map("8").toNone(),
    map("9").toNone(),
    map("0").toNone(),
    map("h").to("tab"),
    map("j").to("h"),
    map("k").to("j"),
    map("l").to("k"),
    map("semicolon").to("l"),
    map("return_or_enter").to("quote"),
    map("y").to("tab", ["left_shift"]),
    map("u").to("y"),
    map("i").to("u"),
    map("o").to("i"),
    map("p").to("o"),
    map("open_bracket").to("p"),
    map("close_bracket").toNone(),
    map("backslash").toNone(),
    map("b").toNone(),
    map("n").to("b"),
    map("m").to("n"),
    map("comma").to("m"),
    map("period").to("comma"),
    map("slash").to("period"),
  ]
}
